#!/bin/sh

FILE=~/documenti/utili/todo-list.txt

read -p "In what line do you want the entry to be written? " LINEA
read -p "Add to the list: " NUOVO

printf "%s\n" >> $FILE

if [ "$NUOVO" != "" ]; [ "$LINEA" = "1" ]; then
    awk -i inplace 'NR==1{print "'$NUOVO'"}1' $FILE
elif [ "$NUOVO" != "" ]; [ "$LINEA" = "2" ]; then
    awk -i inplace 'NR==2{print "'$NUOVO'"}1' $FILE
elif [ "$NUOVO" != "" ]; [ "$LINEA" = "3" ]; then
    awk -i inplace 'NR==3{print "'$NUOVO'"}1' $FILE
elif [ "$NUOVO" != "" ]; [ "$LINEA" = "4" ]; then
    awk -i inplace 'NR==4{print "'$NUOVO'"}1' $FILE
elif [ "$NUOVO" != "" ]; [ "$LINEA" = "5" ]; then
    awk -i inplace 'NR==5{print "'$NUOVO'"}1' $FILE
elif [ "$NUOVO" != "" ]; [ "$LINEA" = "6" ]; then
    awk -i inplace 'NR==6{print "'$NUOVO'"}1' $FILE
elif [ "$NUOVO" != "" ]; [ "$LINEA" = "7" ]; then
    awk -i inplace 'NR==7{print "'$NUOVO'"}1' $FILE
elif [ "$NUOVO" != "" ]; [ "$LINEA" = "8" ]; then
    awk -i inplace 'NR==8{print "'$NUOVO'"}1' $FILE
elif [ "$NUOVO" != "" ]; [ "$LINEA" = "9" ]; then
    awk -i inplace 'NR==9{print "'$NUOVO'"}1' $FILE
elif [ "$NUOVO" != "" ]; [ "$LINEA" = "10" ]; then
    awk -i inplace 'NR==10{print "'$NUOVO'"}1' $FILE
fi

ULTIMA=$(sed -n '$p' $FILE)
if [ "$ULTIMA" = "" ]; then
    sed -i '$d' $FILE   
fi

printf \n
todo-list
