#!/bin/sh
todo-list
printf '\n'
read LINEA

if [ "$LINEA" = "1" ];then
    sed -i '1d' ~/.local/share/todo-list.txt
elif [ "$LINEA" = "2" ];then
    sed -i '2d' ~/.local/share/todo-list.txt
elif [ "$LINEA" = "3" ];then
    sed -i '3d' ~/.local/share/todo-list.txt
elif [ "$LINEA" = "4" ];then
    sed -i '4d' ~/.local/share/todo-list.txt
elif [ "$LINEA" = "5" ];then
    sed -i '5d' ~/.local/share/todo-list.txt
elif [ "$LINEA" = "6" ];then
    sed -i '6d' ~/.local/share/todo-list.txt
elif [ "$LINEA" = "7" ];then
    sed -i '7d' ~/.local/share/todo-list.txt
elif [ "$LINEA" = "8" ];then
    sed -i '8d' ~/.local/share/todo-list.txt
elif [ "$LINEA" = "9" ];then
    sed -i '9d' ~/.local/share/todo-list.txt
elif [ "$LINEA" = "10" ];then
    sed -i '10d' ~/.local/share/todo-list.txt
fi
