#!/bin/sh

# Todo-list file path; edit accordingly.
FILE=~/.local/share/todo-list.txt

# Print the todo-list and read user input. Type the number of the line you want to delete.
todo-list
printf '\n'
read LINE

# Delete selected line.
if [ "$LINE" = "1" ];then
    sed -i '1d' $FILE
elif [ "$LINE" = "2" ];then
    sed -i '2d' $FILE
elif [ "$LINE" = "3" ];then
    sed -i '3d' $FILE
elif [ "$LINE" = "4" ];then
    sed -i '4d' $FILE
elif [ "$LINE" = "5" ];then
    sed -i '5d' $FILE
elif [ "$LINE" = "6" ];then
    sed -i '6d' $FILE
elif [ "$LINE" = "7" ];then
    sed -i '7d' $FILE
elif [ "$LINE" = "8" ];then
    sed -i '8d' $FILE
elif [ "$LINE" = "9" ];then
    sed -i '9d' $FILE
elif [ "$LINE" = "10" ];then
    sed -i '10d' $FILE
fi
